// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3219.Robot_2016.subsystems;

import org.usfirst.frc3219.Robot_2016.RobotMap;

import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Climber extends Subsystem {

	private static final double LEFT_RELEASE = 1.0;
	private static final double RIGHT_RELEASE = -1.0;
	private static final double LEFT_RESET = 0;
	private static final double RIGHT_RESET = 1.0;
	public static final float RIGHT_SERVO_CLOSED = 180.0f;
	public static final float LEFT_SERVO_CLOSED = 0.0f;
	public static final float RIGHT_SERVO_OPEN = 0.0f;
	public static final float LEFT_SERVO_OPEN = 180.0f;
	
	Servo leftServo;
	Servo rightServo;
	Servo testServo;
	
	public Climber() {
		leftServo = RobotMap.pwmServo_4;
		rightServo = RobotMap.pwmServo_3;
		testServo = RobotMap.pwmServo_Test;
		
	}
	
	public void releaseClimber() {
		leftServo.set(LEFT_RELEASE);
		rightServo.set(RIGHT_RELEASE);
		testServo.set(RIGHT_RELEASE);
	}

	public void resetClimber() {
		leftServo.set(LEFT_RESET);
		rightServo.set(RIGHT_RESET);
		testServo.set(RIGHT_RESET);
	}
	
	public void initDefaultCommand() {

	}
}
