// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3219.Robot_2016.subsystems;

import org.usfirst.frc3219.Robot_2016.RobotMap;

import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Climber extends Subsystem {
	private static final double LEFT_RELEASE = 1.0;
	private static final double RIGHT_RELEASE = -1.0;
	private static final double LEFT_RESET = -1.0;
	private static final double RIGHT_RESET = 1.0;
	
	Servo leftServo;
	Servo rightServo;
	
	public Climber() {
		leftServo = RobotMap.pwmServo_4;
		rightServo = RobotMap.pwmServo_5;
	}
	
	public void releaseClimber() {
		leftServo.setPosition(LEFT_RELEASE);
		rightServo.setPosition(RIGHT_RELEASE);
	}

	public void resetClimber() {
		leftServo.setPosition(LEFT_RESET);
		rightServo.setPosition(RIGHT_RESET);
	}
	
	public void initDefaultCommand() {

	}
}
