// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3219.Robot_2016.subsystems;

import org.usfirst.frc3219.Robot_2016.RobotMap;

import edu.wpi.first.wpilibj.Counter;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 * This class is for Putting the ball into the shooter
 */

public class FeedMech extends Subsystem {

	private static final double FEEDER_STOP_SPEED = 0.0;
	private Talon feederMotor = RobotMap.shooterFeederMotor;
	private DigitalInput feederLimitSwitch = RobotMap.feederLimitSwitch;

	public double feederSpeeder = 0.3;

	public FeedMech() {
    	feederMotor.setSafetyEnabled(false);
    	feederMotor.setInverted(true);
	}

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
	public boolean getLimitSwitch() {
		return feederLimitSwitch.get();
	}
	
	public void spinFeeder(double speed) {
		feederMotor.set(speed);
	}
	public void stopFeeder() {
		feederMotor.set(FEEDER_STOP_SPEED);
	}

    public void initDefaultCommand() {
     }
}

