// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3219.Robot_2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static TalonSRX driveRightDriveFront;
	public static TalonSRX driveRightDriveBack;
	public static TalonSRX driveLeftDriveFront;
	public static TalonSRX driveLeftDriveBack;
	
	public static RobotDrive driveDriveMotors;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder baseQuadrature_Encoder_1;
    public static Encoder baseQuadrature_Encoder_2;
    public static SpeedController baseSpeed_Controller_0;
    public static SpeedController baseSpeed_Controller_1;
    public static SpeedController baseSpeed_Controller_2;
    public static SpeedController baseSpeed_Controller_3;
    public static RobotDrive baseRobotDrive41;
    public static SpeedController shooterSpeed_Controller_4;
    public static SpeedController shooterSpeed_Controller_5;
    public static RobotDrive shooterRobotDrive21;
    public static SpeedController feedMechSpeed_Controller_6;
    public static SpeedController feedMechSpeed_Controller_7;
    public static RobotDrive feedMechRobotDrive21;
    public static DigitalInput multiToolLimit_Switch_1;
    public static SpeedController multiToolSpeed_Controller_8;
    public static DigitalInput multiToolLimit_Switch_2;
    public static DigitalInput climberLimitSwitch_1;
    public static SpeedController climberSpeed_Controller_9;
    public static DigitalInput climberLimit_Switch_2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
    	driveRightDriveFront = new TalonSRX(4);// these might be wrong
    	driveRightDriveBack = new TalonSRX(5);
    	
    	driveLeftDriveFront = new TalonSRX(6);
    	driveLeftDriveBack = new TalonSRX(7);
    	
    	driveDriveMotors = new RobotDrive(driveLeftDriveFront, driveLeftDriveBack, driveRightDriveFront, driveRightDriveBack);
    	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        baseQuadrature_Encoder_1 = new Encoder(1, 2, false, EncodingType.k4X);
        LiveWindow.addSensor("Base", "Quadrature_Encoder_1", baseQuadrature_Encoder_1);
        baseQuadrature_Encoder_1.setDistancePerPulse(1.0);
        baseQuadrature_Encoder_1.setPIDSourceType(PIDSourceType.kRate);
        baseQuadrature_Encoder_2 = new Encoder(3, 4, false, EncodingType.k4X);
        LiveWindow.addSensor("Base", "Quadrature_Encoder_2", baseQuadrature_Encoder_2);
        baseQuadrature_Encoder_2.setDistancePerPulse(1.0);
        baseQuadrature_Encoder_2.setPIDSourceType(PIDSourceType.kRate);
        baseSpeed_Controller_0 = new TalonSRX(0);
        LiveWindow.addActuator("Base", "Speed_Controller_0", (TalonSRX) baseSpeed_Controller_0);
        
        baseSpeed_Controller_1 = new TalonSRX(1);
        LiveWindow.addActuator("Base", "Speed_Controller_1", (TalonSRX) baseSpeed_Controller_1);
        
        baseSpeed_Controller_2 = new TalonSRX(2);
        LiveWindow.addActuator("Base", "Speed_Controller_2", (TalonSRX) baseSpeed_Controller_2);
        
        baseSpeed_Controller_3 = new TalonSRX(3);
        LiveWindow.addActuator("Base", "Speed_Controller_3", (TalonSRX) baseSpeed_Controller_3);
        
        baseRobotDrive41 = new RobotDrive(baseSpeed_Controller_0, baseSpeed_Controller_1,
              baseSpeed_Controller_2, baseSpeed_Controller_3);
        
        baseRobotDrive41.setSafetyEnabled(true);
        baseRobotDrive41.setExpiration(0.1);
        baseRobotDrive41.setSensitivity(0.5);
        baseRobotDrive41.setMaxOutput(1.0);
        baseRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        baseRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        shooterSpeed_Controller_4 = new TalonSRX(4);
        LiveWindow.addActuator("Shooter", "Speed_Controller_4", (TalonSRX) shooterSpeed_Controller_4);
        
        shooterSpeed_Controller_5 = new TalonSRX(5);
        LiveWindow.addActuator("Shooter", "Speed_Controller_5", (TalonSRX) shooterSpeed_Controller_5);
        
        shooterRobotDrive21 = new RobotDrive(shooterSpeed_Controller_4, shooterSpeed_Controller_5);
        
        shooterRobotDrive21.setSafetyEnabled(true);
        shooterRobotDrive21.setExpiration(0.1);
        shooterRobotDrive21.setSensitivity(0.5);
        shooterRobotDrive21.setMaxOutput(1.0);
        shooterRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        feedMechSpeed_Controller_6 = new TalonSRX(6);
        LiveWindow.addActuator("Feed Mech", "Speed_Controller_6", (TalonSRX) feedMechSpeed_Controller_6);
        
        feedMechSpeed_Controller_7 = new TalonSRX(7);
        LiveWindow.addActuator("Feed Mech", "Speed_Controller_7", (TalonSRX) feedMechSpeed_Controller_7);
        
        feedMechRobotDrive21 = new RobotDrive(feedMechSpeed_Controller_6, feedMechSpeed_Controller_7);
        
        feedMechRobotDrive21.setSafetyEnabled(true);
        feedMechRobotDrive21.setExpiration(0.1);
        feedMechRobotDrive21.setSensitivity(0.5);
        feedMechRobotDrive21.setMaxOutput(1.0);

        multiToolLimit_Switch_1 = new DigitalInput(6);
        LiveWindow.addSensor("multiTool", "Limit_Switch_1", multiToolLimit_Switch_1);
        
        multiToolSpeed_Controller_8 = new TalonSRX(8);
        LiveWindow.addActuator("multiTool", "Speed_Controller_8", (TalonSRX) multiToolSpeed_Controller_8);
        
        multiToolLimit_Switch_2 = new DigitalInput(7);
        LiveWindow.addSensor("multiTool", "Limit_Switch_2", multiToolLimit_Switch_2);
        
        climberLimitSwitch_1 = new DigitalInput(0);
        LiveWindow.addSensor("Climber", "Limit Switch_1", climberLimitSwitch_1);
        
        climberSpeed_Controller_9 = new TalonSRX(9);
        LiveWindow.addActuator("Climber", "Speed_Controller_9", (TalonSRX) climberSpeed_Controller_9);
        
        climberLimit_Switch_2 = new DigitalInput(5);
        LiveWindow.addSensor("Climber", "Limit_Switch_2", climberLimit_Switch_2);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
