// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3219.Robot_2016;

import org.usfirst.frc3219.Robot_2016.subsystems.Camera;
import org.usfirst.frc3219.Robot_2016.subsystems.Sensors;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Counter;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.PWM;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// drive
	public static Jaguar driveRightDrive;
	public static Jaguar driveLeftDrive;
	public static RobotDrive driveDriveMotors;
	// Encoders
	public static Encoder driveEncoderLeft;
	public static Encoder driveEncoderRight;
	// MultiTool
	public static Victor driveRollerMotorController;
	public static Victor driveMultiToolArmMotor;
	public static Encoder multiToolEncoder;
	public static DigitalInput multiToolLimitSwitch;
	// Shooter
	public static CANTalon driveRightDriveShooter;
	public static CANTalon driveLeftDriveShooter;
	public static Victor shooterFeeder;
	public static DigitalInput feederLimitSwitch;
	// climber
	public static Encoder sensorsArmEncoder;

	public static DigitalInput climberLimitSwitch_1;
	public static SpeedController climberSpeed_Controller_12;
	public static DigitalInput climberLimit_Switch_2;
	public static Servo pwmServo_4;// For ServoController
	public static Servo pwmServo_5;
	// misc
	public static Camera camera;
	public static Counter normalCounter;
	public static DigitalInput lineSeekerInput;
	public static DigitalInput lineFinder;
	public static AnalogInput sensorsUltraSonic1;
	public static AnalogInput sensorsUltraSonic2;
	
	public static void init() {
		try {
			// Drive
			driveRightDrive = new Jaguar(1);
			driveLeftDrive = new Jaguar(0);
			driveDriveMotors = new RobotDrive(driveLeftDrive, driveRightDrive);
			driveDriveMotors.setSafetyEnabled(true);
			driveDriveMotors.setExpiration(0.1);
			driveDriveMotors.setSensitivity(0.5);
			driveDriveMotors.setMaxOutput(1.0);
			// Encoders
			driveEncoderLeft = new Encoder(1, 2, false, EncodingType.k4X);
			driveEncoderLeft.setDistancePerPulse(1.0);
			driveEncoderLeft.setPIDSourceType(PIDSourceType.kRate);
			driveEncoderRight = new Encoder(3, 4, false, EncodingType.k4X);
			driveEncoderRight.setDistancePerPulse(1.0);
			driveEncoderRight.setPIDSourceType(PIDSourceType.kRate);
			sensorsArmEncoder = new Encoder (4, 5, false, EncodingType.k4X);
			LiveWindow.addSensor("Sensors", "ArmEncoder", sensorsArmEncoder);
			sensorsArmEncoder.setDistancePerPulse(0.72434);
			sensorsArmEncoder.setPIDSourceType(PIDSourceType.kRate);
			//MultiTool
			driveRollerMotorController = new Victor(2);
			driveMultiToolArmMotor = new Victor(3);
			multiToolEncoder = new Encoder(5, 6, false, EncodingType.k4X);
			multiToolLimitSwitch = new DigitalInput(6);
			//Shooter
			driveRightDriveShooter = new CANTalon(4);
			driveLeftDriveShooter = new CANTalon(5);
			//Feed Mech
			shooterFeeder = new Victor(8); //incorrect port
			feederLimitSwitch = new DigitalInput(5); //incorrect port
			//Counter
			normalCounter = new Counter(5);
			lineSeekerInput = new DigitalInput(9);
			sensorsUltraSonic1 = new AnalogInput(0);
			// quick release / climber
			climberLimitSwitch_1 = new DigitalInput(0);
			climberLimit_Switch_2 = new DigitalInput(8);
			pwmServo_4 = new Servo(4);
			pwmServo_5 = new Servo(5);

		} catch (Exception e) {
			System.out.println("ERROR ON THE RobotMapInit: " + e.getMessage());
		}
	}
}
